// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDma_xc0m8dmCMM0JlJbfSC20_8adMJSV8',
    appId: '1:1053536670585:web:3a51da9324423a3ce895a8',
    messagingSenderId: '1053536670585',
    projectId: 'acespark-bdc61',
    authDomain: 'acespark-bdc61.firebaseapp.com',
    storageBucket: 'acespark-bdc61.appspot.com',
    measurementId: 'G-BJDD5TPXQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnQNyKSskW1uMDp7VZt1ZNpMXxaFNFkZk',
    appId: '1:1053536670585:android:768a8dfde9f8ae45e895a8',
    messagingSenderId: '1053536670585',
    projectId: 'acespark-bdc61',
    storageBucket: 'acespark-bdc61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpihzp2GC56x1DFNIud7b7GUL39FHP7BI',
    appId: '1:1053536670585:ios:615a37abfdc311a9e895a8',
    messagingSenderId: '1053536670585',
    projectId: 'acespark-bdc61',
    storageBucket: 'acespark-bdc61.appspot.com',
    androidClientId: '1053536670585-g8gb97222t1g3vf05vhkun4tqiu5fiq0.apps.googleusercontent.com',
    iosClientId: '1053536670585-qhug21uguo4bu7uqsdhgdn270t0frkb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.aceSparkV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpihzp2GC56x1DFNIud7b7GUL39FHP7BI',
    appId: '1:1053536670585:ios:615a37abfdc311a9e895a8',
    messagingSenderId: '1053536670585',
    projectId: 'acespark-bdc61',
    storageBucket: 'acespark-bdc61.appspot.com',
    androidClientId: '1053536670585-g8gb97222t1g3vf05vhkun4tqiu5fiq0.apps.googleusercontent.com',
    iosClientId: '1053536670585-qhug21uguo4bu7uqsdhgdn270t0frkb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.aceSparkV1',
  );
}
